# ====== 服务配置 ======
server:
  port: 8066
  tomcat:
    uri-encoding: UTF-8
  servlet:
    # 访问路径
    context-path: /micro-b-server
    # 字符编码
    encoding:
      force: true
      charset: UTF-8
      enabled: true

# ====== 日志配置 ======
logging:
  level:
    root: INFO
    # 指定包日志级别
    com.netflix: DEBUG
    # Spring 日志
    org.springframework.web: TRACE
    #
    okhttp3: TRACE
    # 当前服务日志级别
    org.cloudland.study.micro.b: DEBUG

  file:
    name: logs/micro-b-server.log

# ====== 注册中心&配置中心 ======
spring:
  application:
    name: micro-b-server
  cloud:
    nacos:
      # 服务注册
      discovery:
        # 服務地址
        server-addr: @nacos.server.addr@
        # 命名空间
        namespace: @nacos.server.namespace@
        # 分组
        group: @nacos.server.group@

# ====== MyBatis 配置 ======
mybatis:
  mapper-locations: classpath*:org/cloudland/study/micro/b/server/dao/*Mapper.xml
  type-aliases-package: org.cloudland.study.micro.b.server.dao

# ====== Seata 配置 ======
seata:
  enabled: true
  application-id: micro-b-server
  tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  client:
    rm-report-success-enable: true
    rm-table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
    rm-report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
    rm-async-commit-buffer-limit: 10000 # 异步提交缓存队列长度（默认10000）
    rm:
      lock:
        lock-retry-internal: 10 # 校验或占用全局锁重试间隔（默认10ms）
        lock-retry-times:    30 # 校验或占用全局锁重试次数（默认30）
        lock-retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
    tm-commit-retry-count:   3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
    tm-rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    undo:
      undo-data-validation: true # 二阶段回滚镜像校验（默认true开启）
      undo-log-serialization: jackson # undo序列化方式（默认jackson）
      undo-log-table: undo_log  # 自定义undo表名（默认undo_log）
    log:
      exceptionRate: 100 # 日志异常输出概率（默认100）
    support:
      spring:
        datasource-autoproxy: true
  service:
    # TC 集群（必须与seata-server保持一致）
    vgroup-mapping:
      my_test_tx_group: default
    enable-degrade: false # 降级开关
    disable-global-transaction: false # 禁用全局事务（默认false）
    grouplist:
      default: 127.0.0.1:8091
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  registry:
    #    file:
    #      name: file.conf
    type: nacos
    nacos:
      server-addr: 172.18.7.148:8848
      #      namespace: public
      group : SEATA_GROUP
      cluster: default
  config:
    #    file:
    #      name: file.conf
    type: nacos
    nacos:
      server-addr: 172.18.7.148:8848
      #      namespace: public
      group: SEATA_GROUP